"""
utils/efir_generator.py
Auto-generates a draft E-FIR the moment an incident is marked critical /
left unresolved, pulling the tourist's recent location trail so officers get
a "last known movements" trace, not just a single point.
"""
import secrets
from datetime import datetime
from database.db import get_db


def short_id() -> str:
    return secrets.token_hex(4).upper()


async def generate_efir(incident: dict, user: dict | None, station_jurisdiction: str) -> dict:
    db = get_db()

    recent_trail = await db["Live locations"].find({"userId": incident["userId"]}).sort(
        "recordedAt", -1
    ).to_list(length=20)

    full_name = (user or {}).get("fullName", incident["userId"])
    blockchain_id = (user or {}).get("blockchainId", "N/A")
    coords = incident["location"]["coordinates"]

    narrative = (
        "Automated E-FIR generated by SafeTour system.\n"
        f"Tourist: {full_name} (Blockchain ID: {blockchain_id}).\n"
        f"Incident type: {incident['type']}, severity: {incident['severity']}.\n"
        f"Reported at coordinates [{coords[0]}, {coords[1]}] on {incident.get('createdAt', datetime.utcnow())}.\n"
        f"Description: {incident.get('description') or 'No further details provided by the reporting device.'}\n"
        "This report was filed automatically because the incident remained unresolved past the "
        "safety response window. Please verify with the tourist and dispatch the nearest available unit."
    )

    last_known_locations = []
    for loc in recent_trail:
        coord = (loc.get("snappedLocation") or {}).get("coordinates") or loc["rawLocation"]["coordinates"]
        last_known_locations.append({"coordinates": coord, "timestamp": loc["recordedAt"]})

    now = datetime.utcnow()
    efir = {
        "efirId": f"EFIR-{short_id()}",
        "incidentId": incident["incidentId"],
        "userId": incident["userId"],
        "blockchainId": blockchain_id,
        "stationJurisdiction": station_jurisdiction,
        "narrative": narrative,
        "location": incident["location"],
        "lastKnownLocations": last_known_locations,
        "generatedBy": "SYSTEM_AUTO",
        "status": "draft",
        "filedAt": now,
        "createdAt": now,
        "updatedAt": now,
    }
    await db["efir"].insert_one(efir)
    return efir
